#!/usr/bin/perl

$old_release=$ARGV[0];
$new_release=$ARGV[1];

($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);
$year+=1900;

for ($i=0;$i<2;$i++) {
    if ($ARGV[$i]!~/^[0-9]+\.[0-9]+\.[0-9]+$/) {
	print "Error: please specify two arguments, the old release version and the new release version, of the form 0.0.0\n";
	exit;
    }
}

if (!-f "inputmultiselect-$new_release.js" || !-f "inputmultiselect-$old_release.js") {
    print "Error: javascript file is missing\n";
    exit;
}

open(F,"inputmultiselect-$new_release.js");
@lines=<F>;
close F;
$line=join('',@lines);
$line=~s/\/\*BEGINTEST\*\/.*?\/\*ENDTEST\*\///gs;
open(F,">inputmultiselect-$new_release.js.notest");
print F $line;
close F;

# minify new release js
`jsmin <inputmultiselect-$new_release.js.notest >inputmultiselect-$new_release.min.js.tmp`;
`cat inputmultiselect.copyright.txt|sed 's/%VERSION%/$new_release/g'|sed 's/%YEAR%/$year/g'>inputmultiselect-$new_release.min.js`;
`cat inputmultiselect-$new_release.min.js.tmp >> inputmultiselect-$new_release.min.js`;
`rm inputmultiselect-$new_release.min.js.tmp`;

# pack new release js
`php ~/packer/example-file.php inputmultiselect-$new_release.js.notest inputmultiselect-$new_release.packed.js.tmp`;
`cat inputmultiselect.copyright.txt|sed 's/%VERSION%/$new_release/g'|sed 's/%YEAR%/$year/g'>inputmultiselect-$new_release.packed.js`;
`cat inputmultiselect-$new_release.packed.js.tmp >> inputmultiselect-$new_release.packed.js`;
`rm inputmultiselect-$new_release.packed.js.tmp`;

`rm inputmultiselect-$new_release.js.notest`;

# extract example package
`unzip inputmultiselect-$old_release.zip`;

# build example package directory
`mv inputmultiselect-$old_release inputmultiselect-$new_release`;
`rm inputmultiselect-$new_release/inputmultiselect-$old_release.js inputmultiselect-$new_release/inputmultiselect-$old_release.min.js`;
`cp inputmultiselect-$new_release.js inputmultiselect-$new_release/`;
`cp inputmultiselect-$new_release.min.js inputmultiselect-$new_release/`;
`cat inputmultiselect-$new_release/index.html|sed 's/$old_release/$new_release/g'>inputmultiselect-$new_release/index.html`;
`zip -r inputmultiselect-$new_release.zip inputmultiselect-$new_release/`;
`rm -rf inputmultiselect-$new_release/`;
`cat index.html|sed 's/$old_release/$new_release/g'>index.html.tmp && mv index.html.tmp index.html`;

# move old files
`svn mv inputmultiselect-$old_release.js oldversions/`;
`svn mv inputmultiselect-$old_release.min.js oldversions/`;
`svn mv inputmultiselect-$old_release.packed.js oldversions/`;
`svn mv inputmultiselect-$old_release.zip oldversions/`;

# add new files
`svn add inputmultiselect-$new_release.js inputmultiselect-$new_release.min.js inputmultiselect-$new_release.packed.js inputmultiselect-$new_release.zip`;
