#!/usr/bin/perl

$old_release=$ARGV[0];
$new_release=$ARGV[1];

$jsmin="jsmin";

($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);
$year+=1900;

for ($i=0;$i<2;$i++) {
    if ($ARGV[$i]!~/^[0-9]+\.[0-9]+\.[0-9]+$/) {
	print "Error: please specify two arguments, the old release version and the new release version, of the form 0.0.0\n";
	exit;
    }
}

if (!-f "inputmultiselect-$new_release.js" || !-f "inputmultiselect-$old_release.js") {
    print "Error: javascript file is missing\n";
    exit;
}

open(F,"inputmultiselect-$new_release.js");
@lines=<F>;
close F;
$line=join('',@lines);
$line=~s/\/\*BEGINTEST\*\/.*?\/\*ENDTEST\*\///gs;
open(F,">inputmultiselect-$new_release.js.notest");
print F $line;
close F;

# minify new release js
`$jsmin <inputmultiselect-$new_release.js.notest >inputmultiselect-$new_release.min.js.tmp`;
`cat inputmultiselect.copyright.txt|sed 's/%VERSION%/$new_release/g'|sed 's/%YEAR%/$year/g'>inputmultiselect-$new_release.min.js`;
`cat inputmultiselect-$new_release.min.js.tmp >> inputmultiselect-$new_release.min.js`;
`rm inputmultiselect-$new_release.min.js.tmp`;

# symlink new release
`rm -f inputmultiselect.min.js`;
`ln -s inputmultiselect-$new_release.min.js inputmultiselect.min.js`;

`rm inputmultiselect-$new_release.js.notest`;
